- name: Reload systemd and restart MongoDB
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    daemon_reload: yes
    
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
