#!/usr/bin/env python3
"""
Interactive setup script for iNethi configuration
Helps users configure the system step by step with beautiful colors
"""
import os
import sys
import pathlib
import json
from utils.colors import (
    print_header, print_section, print_step, print_success,
    print_error, print_warning, print_info, print_progress,
    input_prompt, highlight, code
)


def get_user_input(prompt: str, default: str = "", required: bool = True) -> str:
    """Get user input with validation"""
    while True:
        if default:
            user_input = input(f"{prompt} [{default}]: ").strip()
            if not user_input:
                user_input = default
        else:
            user_input = input(f"{prompt}: ").strip()

        if not user_input and required:
            print("This field is required. Please enter a value.")
            continue

        return user_input


def get_environment_choice() -> str:
    """Get environment choice from user"""
    print_section("Environment Selection")
    print_info("Production environment is the only supported option for this public repository.")
    print_info("This ensures secure, production-ready deployments.")
    print_success("✓ Production environment selected")

    return "production"


def get_server_config() -> dict:
    """Get server configuration from user"""
    print_section("Server Configuration")

    server_config = {}
    server_config['ip'] = get_user_input("Server IP address", required=True)
    server_config['user'] = get_user_input("SSH username", "ubuntu", required=True)

    print_info("Authentication method:")
    print_step(1, "Password")
    print_step(2, "SSH Key")

    while True:
        auth_choice = input(input_prompt("Select authentication method (1-2): ")).strip()
        if auth_choice == "1":
            server_config['auth_method'] = "password"
            server_config['auth_value'] = get_user_input("SSH password", required=True)
            break
        elif auth_choice == "2":
            server_config['auth_method'] = "key"
            server_config['auth_value'] = get_user_input("Path to SSH private key", required=True)
            break
        else:
            print_error("Please enter 1 or 2.")

    return server_config


def get_services_config() -> list:
    """Get services configuration from user"""
    print_section("Services Configuration")
    print_info("Available services:")

    services = [
        'azuracast', 'dnsmasq', 'jellyfin', 'keycloak', 'kiwix',
        'moodle', 'nextcloud', 'radiusdesk', 'splash', 'wordpress'
    ]

    for i, service in enumerate(services, 1):
        print(f"  {highlight(str(i))}. {code(service)}")

    print_info("Enter the numbers of services you want to install (comma-separated)")
    print_info("Example: 1,3,5 or 'all' for all services")

    while True:
        choice = input(input_prompt("Services to install: ")).strip().lower()

        if choice == "all":
            print_success(f"✓ All {len(services)} services selected")
            return services

        try:
            selected_indices = [int(x.strip()) - 1 for x in choice.split(',')]
            selected_services = [services[i] for i in selected_indices if 0 <= i < len(services)]

            if not selected_services:
                print_error("No valid services selected. Please try again.")
                continue

            print_success(f"✓ {len(selected_services)} services selected: {', '.join(selected_services)}")
            return selected_services
        except (ValueError, IndexError):
            print_error("Invalid input. Please enter numbers separated by commas.")


def create_env_file(environment: str, server_config: dict, services: list) -> bool:
    """Create .env file with user configuration"""

    env_content = f"""# iNethi Environment Configuration
# Generated by setup script

# Environment Configuration
ENVIRONMENT={environment}

# Server Configuration
DEFAULT_SERVER_IP={server_config['ip']}
DEFAULT_SERVER_USER={server_config['user']}
DEFAULT_AUTH_METHOD={server_config['auth_method']}
DEFAULT_AUTH_VALUE={server_config['auth_value']}

# Ansible Configuration
ANSIBLE_VAULT_PASSWORD_FILE=.vault_password
ANSIBLE_CONFIG=ansible/ansible.cfg

# Logging Configuration
LOG_LEVEL=INFO

# Production Settings
ENABLE_DEBUG_MODE=false
SKIP_SSL_VERIFICATION=false

# Data Storage
DATA_MOUNT=/mnt/data

# Domain Configuration
INETHI_LOCAL_DOMAIN=inethilocal.net

# Docker Configuration
DOCKER_BRIDGE=inethi-bridge-traefik

# Timezone
TIMEZONE=Africa/Johannesburg

# User/Group Configuration
PUID=1000
PGID=1000

# Service Selection
DEFAULT_SERVICES={','.join(services)}

# Monitoring Configuration
ENABLE_MONITORING=true
ENABLE_LOGGING=true

# Security Configuration
ENABLE_FIREWALL=true
ENABLE_SSL_STRICT=true
"""

    try:
        with open('.env', 'w') as f:
            f.write(env_content)

        print_success("Created .env file with your configuration")
        return True
    except Exception as e:
        print_error(f"Error creating .env file: {e}")
        return False


def setup_vault_for_production() -> bool:
    """Setup Ansible vault for production environment with interactive password configuration"""
    print_section("Production Vault Setup")
    print_info("For production environments, you need to set up Ansible Vault for secure password management.")

    # Create vault directory if it doesn't exist
    vault_file = pathlib.Path("ansible/vault/production.yml")
    vault_file.parent.mkdir(parents=True, exist_ok=True)

    # Setup vault encryption password first
    vault_password_file = pathlib.Path(".vault_password")
    default_vault_password = "inethi2024secure"

    print_progress("Setting up vault encryption password...")
    vault_password_input = input(input_prompt(
        f"Enter vault encryption password (or press Enter for default '{default_vault_password}'): ")).strip()
    vault_password = vault_password_input if vault_password_input else default_vault_password

    try:
        with open(vault_password_file, 'w') as f:
            f.write(vault_password)

        # Set secure permissions
        os.chmod(vault_password_file, 0o600)
        print_success("Created vault password file with secure permissions")
    except Exception as e:
        print_error(f"Error creating vault password file: {e}")
        return False

    # Ask if user wants to configure service passwords
    print_info("Service password configuration:")
    print_info("  - Yes: Configure all passwords interactively")
    print_info("  - No: Use default placeholder passwords (can be updated later)")
    configure_passwords = input(input_prompt(
        "Would you like to configure service passwords now? (y/N): ")).strip().lower()

    if configure_passwords in ['y', 'yes']:
        print_progress("Configuring service passwords...")
        print_info("Please enter secure passwords for each service.")

        # Collect all passwords interactively
        passwords = {}

        # Default admin password
        passwords['vault_default_admin_password'] = get_user_input(
            "Enter default admin password (for services like Grafana, Keycloak): ",
            required=True
        )

        # Database passwords
        mysql_root_pass = get_user_input("Enter MySQL root password: ", required=True)
        passwords['vault_mysql_root_password'] = mysql_root_pass
        passwords['vault_mysql_password'] = get_user_input("Enter MySQL user password: ", required=True)

        # Keycloak passwords
        keystore_pass = get_user_input("Enter Keycloak keystore password: ", required=True)
        passwords['vault_keystore_password'] = keystore_pass
        passwords['vault_conf_master_password'] = get_user_input(
            "Enter Keycloak configuration master password: ", required=True)

        # Service-specific passwords
        passwords['vault_moodle_password'] = get_user_input("Enter Moodle password: ", required=True)
        passwords['vault_grafana_admin_password'] = get_user_input("Enter Grafana admin password: ", required=True)

        # Generate auth combination hash (you can use a simple hash for now)
        auth_hash = get_user_input("Enter HTTP authentication hash (or press Enter for default): ", required=False)
        if not auth_hash:
            auth_hash = "$apr1$inethi2024$"
        passwords['vault_auth_combination_hash'] = auth_hash

        # Azuracast passwords
        passwords['vault_azuracast_mysql_password'] = get_user_input("Enter Azuracast MySQL password: ", required=True)
        passwords['vault_azuracast_mysql_root_password'] = get_user_input(
            "Enter Azuracast MySQL root password: ", required=True)
        passwords['vault_azuracast_letsencrypt_email'] = get_user_input(
            "Enter Azuracast Let's Encrypt email: ", required=True)

        # WordPress passwords
        wp_db_pass = get_user_input("Enter WordPress database password: ", required=True)
        passwords['vault_wordpress_db_password'] = wp_db_pass
        passwords['vault_wordpress_db_root_password'] = get_user_input(
            "Enter WordPress database root password: ", required=True)

        # RADIUSdesk passwords
        passwords['vault_radiusdesk_db_password'] = get_user_input(
            "Enter RADIUSdesk database password: ", required=True)
        passwords['vault_radiusdesk_db_root_password'] = get_user_input(
            "Enter RADIUSdesk database root password: ", required=True)
    else:
        print_info("Using default placeholder passwords for all services.")
        print_info("You can update them later with: ansible-vault edit ansible/vault/production.yml")
        print_info("Default values will be used for: admin passwords, database passwords, keystore passwords, etc.")

        # Load default passwords from JSON file
        try:
            with open('default_passwords.json', 'r') as f:
                passwords = json.load(f)
            print_success("✓ Loaded default passwords from default_passwords.json")
        except FileNotFoundError:
            print_error("default_passwords.json not found. Using hardcoded defaults.")
            # Fallback to hardcoded defaults
            passwords = {
                'vault_default_admin_password': 'CHANGE_ME_PRODUCTION_PASSWORD',
                'vault_mysql_root_password': 'CHANGE_ME_MYSQL_ROOT_PASSWORD',
                'vault_mysql_password': 'CHANGE_ME_MYSQL_PASSWORD',
                'vault_keystore_password': 'CHANGE_ME_KEYSTORE_PASSWORD',
                'vault_conf_master_password': 'CHANGE_ME_CONF_MASTER_PASSWORD',
                'vault_moodle_password': 'CHANGE_ME_MOODLE_PASSWORD',
                'vault_grafana_admin_password': 'CHANGE_ME_GRAFANA_PASSWORD',
                'vault_auth_combination_hash': '$apr1$CHANGE_ME_HASH',
                'vault_azuracast_mysql_password': 'CHANGE_ME_AZURACAST_MYSQL_PASSWORD',
                'vault_azuracast_mysql_root_password': 'CHANGE_ME_AZURACAST_ROOT_PASSWORD',
                'vault_azuracast_letsencrypt_email': 'admin@inethilocal.net',
                'vault_wordpress_db_password': 'CHANGE_ME_WORDPRESS_DB_PASSWORD',
                'vault_wordpress_db_root_password': 'CHANGE_ME_WORDPRESS_ROOT_PASSWORD',
                'vault_radiusdesk_db_password': 'CHANGE_ME_RADIUSDESK_DB_PASSWORD',
                'vault_radiusdesk_db_root_password': 'CHANGE_ME_RADIUSDESK_ROOT_PASSWORD'
            }
        except json.JSONDecodeError as e:
            print_error(f"Error parsing default_passwords.json: {e}")
            return False

    # Create vault content with actual passwords
    vault_content = f"""# Production Vault File
# This file contains encrypted secrets for production environment
# To encrypt this file: ansible-vault encrypt ansible/vault/production.yml
# To edit this file: ansible-vault edit ansible/vault/production.yml

# Default admin credentials
vault_default_admin_password: "{passwords['vault_default_admin_password']}"

# Database passwords
vault_mysql_root_password: "{passwords['vault_mysql_root_password']}"
vault_mysql_password: "{passwords['vault_mysql_password']}"

# Keycloak passwords
vault_keystore_password: "{passwords['vault_keystore_password']}"
vault_conf_master_password: "{passwords['vault_conf_master_password']}"

# Service-specific passwords
vault_moodle_password: "{passwords['vault_moodle_password']}"
vault_grafana_admin_password: "{passwords['vault_grafana_admin_password']}"
vault_auth_combination_hash: "{passwords['vault_auth_combination_hash']}"

# Azuracast passwords
vault_azuracast_mysql_password: "{passwords['vault_azuracast_mysql_password']}"
vault_azuracast_mysql_root_password: "{passwords['vault_azuracast_mysql_root_password']}"
vault_azuracast_letsencrypt_email: "{passwords['vault_azuracast_letsencrypt_email']}"

# WordPress passwords
vault_wordpress_db_password: "{passwords['vault_wordpress_db_password']}"
vault_wordpress_db_root_password: "{passwords['vault_wordpress_db_root_password']}"

# RADIUSdesk passwords
vault_radiusdesk_db_password: "{passwords['vault_radiusdesk_db_password']}"
vault_radiusdesk_db_root_password: "{passwords['vault_radiusdesk_db_root_password']}"
"""

    try:
        with open(vault_file, 'w') as f:
            f.write(vault_content)
        print_success("Created production vault file with configured passwords")
    except Exception:
        print_error("Error creating vault file")
        return False

    # Vault password file already created above, no need to create again

    # Encrypt the vault file
    print_progress("Encrypting vault file...")
    try:
        import subprocess
        result = subprocess.run([
            'ansible-vault', 'encrypt', str(vault_file)
        ], capture_output=True, text=True)

        if result.returncode == 0:
            print_success("Vault file encrypted successfully")
        else:
            print_warning("Could not automatically encrypt vault file")
            print_info("You can encrypt it manually with: ansible-vault encrypt ansible/vault/production.yml")
    except Exception:
        print_warning("Could not automatically encrypt vault file")
        print_info("You can encrypt it manually with: ansible-vault encrypt ansible/vault/production.yml")

    return True


def run_setup() -> bool:
    """Run the complete setup process"""
    print_header("iNethi Configuration Setup", "Interactive setup for production deployments")

    # Check if .env already exists
    if pathlib.Path('.env').exists():
        overwrite = input(input_prompt("Configuration file .env already exists. Overwrite? (y/N): ")).strip().lower()
        if overwrite != 'y':
            print_info("Setup cancelled.")
            return False

    # Get configuration from user
    environment = get_environment_choice()
    server_config = get_server_config()
    services = get_services_config()

    # Create .env file
    if not create_env_file(environment, server_config, services):
        return False

    # Setup vault for production (required)
    if not setup_vault_for_production():
        return False

    print_success("🎉 Configuration setup completed successfully!")
    return True


def run_vault_setup() -> bool:
    """Run only vault setup process"""
    print_header("iNethi Vault Setup", "Setting up secure password management")

    # Setup vault for production
    if not setup_vault_for_production():
        return False

    print_success("🎉 Vault setup completed successfully!")
    return True


def main():
    """Main setup function"""
    success = run_setup()

    if success:
        # Final instructions
        print_header("Setup Complete", "Your iNethi configuration is ready!")

        print_info("Next steps:")
        print_step(1, "Review and edit .env file if needed")
        print_step(2, "Edit ansible/vault/production.yml with your passwords: " +
                   code("ansible-vault edit ansible/vault/production.yml"))
        print_step(3, "Run validation: " + code("python3 validate_config.py"))
        print_step(4, "Start deployment: " + code("python3 main.py"))

        print()
        print_info("Your iNethi platform is ready for production deployment.")
        return 0
    else:
        return 1


if __name__ == "__main__":
    sys.exit(main())
