- name: Copy RADIUSdesk docker-compose file
  template:
    src: docker-compose.yml
    dest: "{{ DATA_MOUNT }}/radiusdesk/docker-compose.yml"
    mode: "0644"

- name: Start RADIUSdesk with Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ DATA_MOUNT }}/radiusdesk"
    state: present
    restarted: yes
