---
- name: Copy RADIUSdesk database configuration files
  copy:
    src: "{{ role_path }}/files/db_conf/"
    dest: "{{ DATA_MOUNT }}/radiusdesk/db_conf/"
    mode: "0644"

- name: Copy RADIUSdesk database startup files
  copy:
    src: "{{ role_path }}/files/db_startup/"
    dest: "{{ DATA_MOUNT }}/radiusdesk/db_startup/"
    mode: "0644"
