services:
    web:
        container_name: inethi-radio
        image: 'ghcr.io/azuracast/azuracast:latest'
        env_file: azuracast.env
        environment:
            LANG: '${LANG:-en_US.UTF-8}'
            AZURACAST_DC_REVISION: 14
            AZURACAST_VERSION: '${AZURACAST_VERSION:-latest}'
            AZURACAST_SFTP_PORT: '${AZURACAST_SFTP_PORT:-2022}'
            NGINX_TIMEOUT: '${NGINX_TIMEOUT:-1800}'
            LETSENCRYPT_HOST: '${LETSENCRYPT_HOST:-}'
            LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL:-}'
            PUID: '${AZURACAST_PUID:-1000}'
            PGID: '${AZURACAST_PGID:-1000}'
        volumes:
            - '${UPLOADS_VOLUME}:/var/azuracast/uploads'
            - '${STATION_VOLUME}:/var/azuracast/stations'
            - '${SHOUT2CAST_VOLUME}:/var/azuracast/servers/shoutcast2'
            - '${STEREO_TOOL_VOLUME}:/var/azuracast/servers/stereo_tool'
            - '${GEOLITE_VOLUME}:/var/azuracast/geoip'
            - '${SFTPGO_VOLUME}:/var/azuracast/sftpgo/persist'
            - '${BACKUP_VOLUME}:/var/azuracast/backups'
            - '${ACME_VOLUME}:/var/azuracast/acme'
            - '${DB_VOLUME}:/var/lib/mysql'
        restart: unless-stopped
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        logging:
            options:
                max-size: 1m
                max-file: '5'
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.azuracast.rule=Host(`radio.inethilocal.net`)"
            - "traefik.http.routers.azuracast.entrypoints=websecure"
networks:
  default:
    external:
      name: "inethi-bridge-traefik"

