[acct_updates]
update_interval_min = 5
check_interval_sec = 60
state_file = /var/lib/captive-portal/portal_state.json

[radius_server]
radius_server = 164.160.89.129
radius_secret = testing123
radius_auth_port = 1812
radius_acct_port = 1813
timeout = 5

[nas_info]
nas_ip_address = 192.168.8.160
nas_identifier = iNethi-NAS-01
nas_port_type  = Wireless-802.11
rd_captive_portal_version =  1.0

[captive_portal]
subnet = 10.45.0.0/16
gateway = 10.45.0.1
redirect_ip = 10.45.0.1
redirect_http_port = 3990
redirect_https_port = 4990
state_file = /var/lib/captive-portal/portal_state.json
overrides_file = /var/lib/captive-portal/device_overrides.json
device_timeout = 180
max_devices = 100
log_level = DEBUG

[walled_garden]
entries_csv = 192.168.8.0/24,164.160.89.129


[traffic_shaping]
bw_iface = enp0s3
ifb_iface = ifb0
ibw_total = 100mbit

