- name: Create the Grafana container
  docker_container:
    name: inethi-grafana
    image: grafana/grafana:latest
    restart_policy: unless-stopped
    state: started
    env:
      GF_SECURITY_ADMIN_USER: "{{ GF_SECURITY_ADMIN_USER }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ GF_SECURITY_ADMIN_PASSWORD }}"
    volumes:
      - "{{ DATA_MOUNT }}/grafana:/var/lib/grafana"
    labels:
      traefik.enable: "true"
      traefik.http.routers.grafana.rule: "Host(`grafana.{{ INETHI_LOCAL_DOMAIN }}`)"
      traefik.http.routers.grafana.entrypoints: "websecure"
    networks:
      - name: "{{ BRIDGE }}"