---
- name: Create folders and download ACME
  import_tasks: pre-requisites.yml
- name: Create Traefik Docker container
  import_tasks: traefik-container.yml
- name: Create Grafana Docker container
  import_tasks: grafana.yml
- name: Create Prometheus Docker container
  import_tasks: prometheus.yml
- name: Create InfluxDB container
  import_tasks: influxdb.yml