---
- name: Create Hello iNethi directory
  file:
    path: "{{ item }}"
    state: directory
    mode: '0745'
  with_items:
    - "{{ DATA_MOUNT }}/hello_inethi"
    - "{{ DATA_MOUNT }}/hello_inethi/html"
