---
- name: Prerequisites of Open5GS-NMS
  import_tasks: prerequisites.yml
- name: Checkout the Open5GS Repo
  import_tasks: repo_checkout.yml
- name: Build & Deploy Docker Images
  import_tasks: build_deploy.yml
