---
- name: Create Traefik dynamic configuration directory
  ansible.builtin.file:
    path: "{{ DATA_MOUNT }}/traefik/dynamic"
    state: directory
    mode: '0755'

- name: Configure Open5GS NMS in Traefik
  ansible.builtin.template:
    src: open5gs-nms.toml.j2
    dest: "{{ DATA_MOUNT }}/traefik/dynamic/open5gs-nms.toml"
    mode: '0644'
