global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'traefik'
    static_configs:
      - targets: ['inethi-traefikssl:8080']
    metrics_path: '/metrics'

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [ icmp ]
    scrape_interval: 30s
    static_configs:
      - targets:
          - 8.8.8.8
          - 1.1.1.1
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: inethi-blackbox-exporter:9115

