---
- name: Check if Docker is installed
  command: docker --version
  register: docker_installed
  ignore_errors: yes

- name: Install Docker and Docker Compose
  block:
    - name: Install required packages
      apt:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
          - ca-certificates
          - curl

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Set up the stable repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker Packages
      apt:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
    - name: Ensure docker group exists
      group:
        name: docker
        state: present

    - name: Add user to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Run Docker Hello World container
      docker_container:
        name: hello-world
        image: hello-world
        state: started
    - name: Enable and start Docker services
      systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - docker.service
        - containerd.service
    - name: Reboot the system to apply group changes
      reboot:
        msg: "Rebooting to apply group changes"
        connect_timeout: 60
  when: docker_installed is failed