{
 "title": "Blackbox exporter  - multiple locations",
 "description": "Visualizes blackbox exporter metrics running in multiple locations while considering the consensus",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(probe_success, instance)"
    }
   },
   {
    "name": "location",
    "query": {
     "query": "label_values(probe_success, location)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current status",
   "type": "grafana-polystat-panel",
   "description": "Current status by location ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{location}}"
    }
   ]
  },
  {
   "title": "Percent uptime over the last week",
   "type": "stat",
   "description": "Percent uptime per device over the week",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=~\"$instance\"}[7d])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Status history ",
   "type": "timeseries",
   "description": "Status history by location consens",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (instance) (probe_success{instance=~\"$instance\"}) / scalar(count(count by (location) (probe_success)))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}