version: '3'
services:

  radiusdesk:
    build:
      context: ./
      dockerfile: Dockerfile-build-radiusdesk
      args:
        radiusdesk_volume: /mnt/data/radius_desk
    container_name: inethi-radiusdesk

    environment:
      - "PHP_INI_SCAN_DIR=:/p/gd"
      - "PHP.cgi.fix_pathinfo=1"
      - "PHP_SELF=/index.php"
      - "PHP_INI_SCAN_DIR=:/p/sqlite3"
    restart: unless-stopped

    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.radiusdesk.rule=Host(`radiusdesk.inethilocal.net`)"
        - "traefik.http.routers.radiusdesk.entrypoints=websecure"

    depends_on:
      - "rdmariadb"

    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"

  rdmariadb:
    container_name: inethi-radiusdesk-mariadb
    image: docker.io/bitnami/mariadb:10.5

    restart: unless-stopped
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
      - "MARIADB_USER=rd"
      - "MARIADB_DATABASE=rd"
      - "MARDIADB_PASSWORD=rd"

    volumes:
      - /mnt/data/radius_desk/db_conf/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
      - rd_data:/bitnami/mariadb
      - /mnt/data/radius_desk/db_startup:/tmp

volumes:
  rd_data:


networks:
  default:
    external:
      name: "inethi-bridge-traefik"




