- name: Deploy AzuraCast
  hosts: localserver
  become: true
  gather_facts: yes

  vars:
    AZURACAST_MNT: "/mnt/data/azuracast"
    TEMP_MNT: "/mnt/data/temp"

  tasks:
    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0777'
      with_items:
        - "{{ TEMP_MNT }}"
        - "{{ AZURACAST_MNT }}"

    - name: Copy files to Server
      copy:
        src: "{{ playbook_dir }}/resources/azuracast/"
        dest: "{{ TEMP_MNT }}/"

    - name: build the container
      command: "docker compose -f {{ TEMP_MNT }}/docker-compose.yml up -d"
    - name: Wait (3 min) for the Radio to be initialised
      pause:
        seconds: 180

    - name: Delete TEMP_MNT directory
      file:
        path: "{{ TEMP_MNT }}"
        state: absent

    - name: Set permissions on AzuraCast directory
      ansible.builtin.file:
        path: "{{ AZURACAST_MNT }}"
        state: directory
        recurse: yes
        mode: '0777'

    - name: Restart AzuraCast container
      ansible.builtin.command:
        cmd: "docker restart inethi-radio"

    - name: Wait (3 min) for the Radio to be up
      pause:
        seconds: 180



