name: Checks

on:
  push:
    branches:
      - "**"  # Run on push to all branches

jobs:
  lint:
    name: Lint with flake8
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: |
          ./run_flake8.sh || exit 1
